version: '3.8'

services:
  backend:
    container_name: "rps.backend"
    build:
      context: .
      dockerfile: RockPaperScissors.WebApi/Dockerfile
    ports:
      - 5000:8080
    environment:
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
  frontend:
    container_name: "rps.frontend"
    image: nginx:alpine
    volumes:
      - ./frontend:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
  redis:
    container_name: "rps.redis"
    image: redis:alpine
    ports:
      - 6379:6379